### ISSUE TITLE
Bug on tag v0.8.0! Wrong version on quay.io/csiaddons/k8s-controller

### ISSUE THREAD

**Issue by JWebDev** [csi-addons/kubernetes-csi-addons#607] opened 2024-06-28 05:15 UTC
Hi,

you have a typical error in tag v0.8.0.

When you install the controller
`kubectl create -f https://raw.githubusercontent.com/csi-addons/kubernetes-csi-addons/v0.8.0/deploy/controller/setup-controller.yaml`
Exactly it is already 3 days since this deployment will not work. Since this deployment specifies the version `quay.io/csiaddons/k8s-controller:latest`

The latest version has new resources as of today. For example `VolumeGroupReplicationContent`.
So the deployment in `v0.8.0` will simply not start.

```
2024-06-28T05:01:59.673Z ERROR controller-runtime.source.EventHandler if kind is a CRD, it should be installed before calling Start {"kind": "VolumeGroupReplicationContent.replication.storage.openshift.io", "error": "no matches for kind \"VolumeGroupReplicationContent\" in version \"replication.storage.openshift.io/v1alpha1\""}"}
```

In the **v0.8.0** tag you need to change the version from `k8s-controller:latest` to **`k8s-controller:v0.8.0`**

I tried for 2 hours today and couldn't figure out what the reason was.

**Comment by Madhu-1** [comment] 2024-06-28 05:39
Closing as duplicate of https://github.com/csi-addons/kubernetes-csi-addons/issues/600

**Closed by Madhu-1** 2024-06-28 05:39 UTC
